### PR TITLE
Add $apply, include dist, autovivify on nil

### PR DESCRIPTION
**Pull request by GeKorm**
Hello, thanks for making this library that solves our frustrations!

This PR adds 3 features:
- The `$apply` method
- Autovivify on nil: `view === undefined || view === null`
- Include built files so that the library can be added directly from git

I am not sure if auto-vivifying on null is such a good idea since it's usually present in a collection intentionally. However, without it we had to resort to the same deep checks as with [immutability-helper](https://github.com/kolodny/immutability-helper). Maybe it could be an option?

I'll gladly make changes or add more tests if needed.

### CODE REVIEW

**Comment by hoytech** [comment]
Thank you very much! `$apply` was something I've been meaning to get to, much appreciated.

Auto-vivify on null makes sense to me and I have no problem with it.

Lastly, I'm not really used to checking build outputs into the repo and I didn't seem to need it for npm publishing so I didn't. But if it makes usage easier I have no problem with it.

Thank you very much!

**Comment by hoytech** [comment]
Just going to check if there's anything else we should test and then I'll push to npm. Looks good so far though.

**Comment by GeKorm** [comment]
Wow that was quick! Thanks @hoytech

**Comment by hoytech** [comment]
I released 1.1.0, thanks again!

**Pull request merged**
