### PR TITLE
No shallow copy on update with same value primitive

### PR DESCRIPTION
**Pull request by GeKorm**
This preserves reference equality without doing deep checks. It's in line with immutability-helper as far as I can tell.

Addresses #3 and the TODO on the readme which I should've read :)

### CODE REVIEW

**Comment by hoytech** [comment]
Wow this is awesome! Just reading through it now and will most likely merge in a minute. Thank you!

**Comment by hoytech** [comment]
Looks good. A few points:

1) There are some cases where it could preserve equality but doesn't. For example, consider `$unset`ing a key that doesn't exist.
2) Just curious why you changed `throw(new Error("..."))` to `throw new Error('...')` in one spot. If this is preferable for some reason, I'll change all the other places to match this style.
3) Thanks for adding tests. I think we should rename the `apply_primitive_update` to `apply_update_unchanged` and remove the 4th argument since it should always be the same as the 2nd.

I'll merge your change and then add a few more commits on top and then cut a release.

Thank you so much (again)!

**Comment by hoytech** [comment]
I pushed a few commits that make the changes I described above. Cheers!

**Comment by GeKorm** [comment]
Thanks for your feedback! I agree with all points.
About no 2, my editor must've changed it on paste! Sorry, it was accidental.

**Comment by hoytech** [comment]
No worries. 1.2.0 has been uploaded to npm. :)

**Pull request merged**
